services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "app_music"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_music"]
      interval: 5s
      timeout: 5s
      retries: 10

  back:
    build: ./back
    volumes:
      - type: bind
        source: ./back
        target: /app

    ports:
      - "8000:8000"

    depends_on:
      db: 
        condition: service_healthy

  front:
    build: ./front
    volumes:
      - ./front:/app
      - /app/node_modules

    ports:
      - "4200:4200"

volumes:
  postgres_data:
  