# Generated by Django 6.0.7 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0005_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='category',
        ),
        migrations.AddField(
            model_name='music',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app_back.category'),
        ),
    ]
