# Generated by Django 6.0.7 on 2026-08-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0006_remove_music_category_music_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='categories',
            new_name='category',
        ),
    ]
