# Generated by Django 6.0.7 on 2026-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0007_rename_categories_music_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='image/')),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
