# Generated by Django 6.0.7 on 2026-09-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='music',
            name='image_filename',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
