# Generated by Django 6.0.7 on 2026-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0009_music_image_file_music_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
