# Generated by Django 6.0.7 on 2026-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0010_alter_music_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='count_download',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='count_like',
            field=models.IntegerField(null=True),
        ),
    ]
