# Generated by Django 6.0.7 on 2026-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0011_music_count_download_music_count_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='count_download',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='count_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
