# Generated by Django 6.0.7 on 2026-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0012_alter_music_count_download_alter_music_count_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('discord_link', models.URLField(blank=True)),
                ('twitch_link', models.URLField(blank=True)),
                ('tiktok_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
    ]
