# Generated by Django 6.0.7 on 2026-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0013_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
